### ISSUE TITLE
Apollo stopped assembling

### ISSUE THREAD

**Issue by flymedllva** [skiptools/skip#415]
[Apollo & ApolloAPI](https://github.com/apollographql/apollo-ios) was built in native mode with bridging disabled in 1.3.10, but stopped doing so in 1.5.5
```yaml
skip:
  mode: 'native'
  bridging: false
```
Error
```
ApolloAPI/JSONDecodingError.swift:18:8: error: associated value 'couldNotConvert(value:to:)' of 'Sendable'-conforming enum 'JSONDecodingError' has non-sendable type '(value: AnyHashable, to: any Any.Type)'
```

It would be cool to get a stable working GraphQL client for skip

**Comment by marcprux** [comment]
Apollo was working? AFAIK, Apollo doesn't even support Linux (https://github.com/apollographql/apollo-ios/issues/3410), so I would be surprised if it was building for Android. In any case, I doubt this would be related to the skip version, since that error is a native build error. Is it possible that you successfully built an [older version](https://github.com/apollographql/apollo-ios/releases) of Apollo, like 1.20.0 (I notice that 1.21.0 was just released last night.

> It would be cool to get a stable working GraphQL client for skip

https://github.com/GraphQLSwift/GraphQL supports Android as of https://github.com/GraphQLSwift/GraphQL/pull/161, so you might be able to use that.

There are some other GraphQL packages listed at https://swift-everywhere.org, although I don't know of any that have been tested.

**Comment by flymedllva** [comment]
If you build Apollo and ApolloAPI packages separately, not the whole library, they were built, they were enough if you do not use SQL cache, which just does not allow to build under Linux

Here is a screenshot of the package build separately on the previous version of skip

<img width="611" alt="Image" src="https://github.com/user-attachments/assets/267201db-dc60-4e9b-9b97-5e6ae2d02703" />

It looks like something changed in skip, since after trying to upgrade, these packages stopped building. But, as I understand, you are not going to consider cases when building the whole package fails under Linux (this information is not in Swift Package Index). I hope this information can be useful to you in some way.

But thanks for answering anyway!

**Comment by marcprux** [comment]
Can you post the errors you are now seeing if you try building with `skip android build --configuration debug -E --product Apollo`?

Do you recall what version it worked with previously? As I say, I'm surprised that it ever built successfully, since it looks like it uses `URLSession` without `import FoundationNetworking`.

It is possible that something in skip broke it, but note that `skip android build` is simply a front-end to natively building against the Android SDK (as you can see if you build with the `--verbose` flag).

**Comment by flymedllva** [comment]
To build on the old version of skip, I copied Apollo & ApolloAPI to Sources, added skip.yml and dependencies to Package.swift. 

I attach [Package.resolved](https://github.com/user-attachments/files/19983376/Package.resolved.log) with which I built

When trying to upgrade to the latest version, I catch these build errors: [skip-build-apollo-api.log](https://github.com/user-attachments/files/19983435/skip-build-apollo-api.log)

> https://github.com/GraphQLSwift/GraphQL supports Android as of https://github.com/GraphQLSwift/GraphQL/pull/161, so you might be able to use that.

At first glance it looks like a server, not a client, perhaps I am wrong as I have not delved into the structure of the package. But this issue https://github.com/GraphQLSwift/GraphQL/issues/137 hints that there's no client here.

**Comment by marcprux** [comment]
I didn't realize you wee copying the files into your project — I thought that you were just depending on `apollo-ios` directly.

It looks like most of those errors are concurrency related. If you set `swiftLanguageVersions: [ .v5  ]` in your Package.swift, does it change anything? Alternatively, you could all some @preconcurrency annotations to the failing types, which might get around those issues.

**Comment by flymedllva** [comment]
It seems skip init has updated Swift from version 5 to 6. If you select 5.9 everything is built. Then we can assume that the package stopped working with the new Swift version and the problem is not with skip. Thanks for your help!
Indeed part of Apollo can be built under Linux and it works via skip, it is enough to use the client without SQL cache
